### ISSUE TITLE
nil pointer exception caused by parse.parseText()

### ISSUE THREAD

**Issue by tsukuha** [murosan/shogi-proxy-server#10]
# 概要
parse.TextFromStringType()内で呼び出す、parse.parseText()で segmentation fault が発生して、将棋エンジンが読み込めない。

# 実行環境
MacOS Monterey 12.2.1
CPU: Apple M1
go: go1.19 darwin/amd64

# 補足
該当の戻り値を空文字列で置き換えることで動作はしたので単純にアクセス方法の問題かと思います。

# エラーログ

## エラー検証用のファイル
`app/lib/usi/parse/option.go` ファイルを以下のコードに編集して発生したエラーになります。
編集した行は、142行目以降です。
 
```go:option.go
package parse

import (
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/murosan/shogi-board-server/app/domain/entity/engine"
)

// Button generates new Button and returns it from the given string.
func Button(s string) (*engine.Button, error) {
	res := buttonRegex.FindAllStringSubmatch(strings.TrimSpace(s), -1)

	if len(res) == 0 || len(res[0]) < 2 {
		msg := "failed to parse button. given=" + s + "\n" + usiOptionFormat
		return nil, errors.New(msg)
	}

	return &engine.Button{Name: res[0][1]}, nil
}

// Check generates new Check and returns it from the given string.
func Check(s string) (*engine.Check, error) {
	res := checkRegex.FindAllStringSubmatch(strings.TrimSpace(s), -1)

	if len(res) == 0 || len(res[0]) < 3 {
		msg := "failed to parse check. input = " + s + usiOptionFormat
		return nil, errors.New(msg)
	}

	b := res[0][2] == "true"
	return &engine.Check{Name: res[0][1], Value: b, Default: b}, nil
}

// Range generates new Range and returns it from the given string.
func Range(s string) (*engine.Range, error) {
	res := spinRegex.FindAllStringSubmatch(strings.TrimSpace(s), -1)

	errMsg := "failed to parse range. given=" + s + usiOptionFormat

	if len(res) == 0 || len(res[0]) < 5 {
		return nil, errors.New(errMsg)
	}

	init, err := strconv.Atoi(res[0][2])
	if err != nil {
		msg := errMsg + "\nDefault was not int. Value: " + res[0][2]
		return nil, errors.New(msg)
	}

	min, err := strconv.Atoi(res[0][3])
	if err != nil {
		msg := errMsg + "\nMin was not int. Value: " + res[0][3]
		return nil, errors.New(msg)
	}

	max, err := strconv.Atoi(res[0][4])
	if err != nil {
		msg := errMsg + "\nMax was not int. Value: " + res[0][4]
		return nil, errors.New(msg)
	}

	if min > max {
		msg := fmt.Sprintf(
			"%s\n%s Min value is not lesser than or equal to Max. Min: %d, Max: %d",
			errMsg,
			s,
			min,
			max,
		)
		return nil, errors.New(msg)
	}

	if init < min || init > max {
		msg := fmt.Sprintf(
			"%s\n%s Default value is not in range. Default: %d, Min: %d, Max: %d",
			errMsg,
			s,
			init,
			min,
			max,
		)
		return nil, errors.New(msg)
	}

	return &engine.Range{
		Name:    res[0][1],
		Value:   init,
		Default: init,
		Min:     min,
		Max:     max,
	}, nil
}

// Select generates new Select and returns it from the given string.
func Select(s string) (*engine.Select, error) {
	res := selectRegex.FindAllStringSubmatch(strings.TrimSpace(s), -1)

	errMsg := "failed to parse select. input = " + s + usiOptionFormat

	if len(res) == 0 || len(res[0]) < 4 {
		return nil, errors.New(errMsg)
	}

	init := res[0][2]
	vars := strings.Split(res[0][3], "var")

	if len(vars) < 2 {
		msg := errMsg + "\nNumber of vars must be at least one."
		return nil, errors.New(msg)
	}

	vars = vars[1:] // trim head because it's a space
	valid := false  // flag to check if the vars contains default

	for i, v := range vars {
		vars[i] = strings.TrimSpace(v)
		valid = valid || vars[i] == init
	}

	// vars にデフォルト値がない場合はエラー
	if !valid {
		msg := fmt.Sprintf(
			"%s\n Default value of Select was not in vars. Default: %s, Vars: %v",
			errMsg,
			init,
			vars,
		)
		return nil, errors.New(msg)
	}

	return &engine.Select{
		Name:    res[0][1],
		Value:   init,
		Default: init,
		Vars:    vars,
	}, nil
}

// TextFromStringType generates new Text and returns it from the given string.
func TextFromStringType(s string) (*engine.Text) {
	res := stringRegex.FindAllStringSubmatch(strings.TrimSpace(s), -1)
	// errMsg := "failed to parse string. input = " + s + usiOptionFormat
	return parseText(res)
}

// TextFromFilenameType generates new Text and returns it from the given string.
func TextFromFilenameType(s string) (*engine.Text) {
	res := fileNameRegex.FindAllStringSubmatch(strings.TrimSpace(s), -1)
	// errMsg := "failed to parse filename. input = " + s + usiOptionFormat
	return parseText(res)
}

func parseText(res [][]string) (*engine.Text) {

	return &engine.Text{
		Name:    res[0][1],
		Value:   res[0][2],
		Default: res[0][2],
	}
}
```

## ログ
```
panic: runtime error: index out of range [0] with length 0

goroutine 36 [running]:
github.com/murosan/shogi-board-server/app/lib/usi/parse.parseText(...)
	/shogi-board-server/app/lib/usi/parse/option.go:159
github.com/murosan/shogi-board-server/app/lib/usi/parse.TextFromStringType({0xc00002a1b0?, 0x2e?})
	/shogi-board-server/app/lib/usi/parse/option.go:146 +0x145
github.com/murosan/shogi-board-server/app/domain/service.(*engineControlService).Connect.func1({0xc00027234e, 0x2e, 0xcb2})
	/shogi-board-server/app/domain/service/engine_control.go:151 +0xe70
github.com/murosan/shogi-board-server/app/domain/infrastructure.(*connector).receive(0xc000334050)
	shogi-board-server/app/domain/infrastructure/connection.go:88 +0x10c
created by github.com/murosan/shogi-board-server/app/domain/infrastructure.(*connector).Connect
	/shogi-board-server/app/domain/infrastructure/connection.go:47 +0x85
```

**Comment by tsukuha** [comment]
同じエラーのissueがclosedして解決していたので、closeします。
お手数をおかけしました。
https://github.com/murosan/shogi-board-server/issues/6#issue-1251132189

**Comment by murosan** [comment]
困ってる人が複数人いるということで、 `<empty>` がなくてもエラーが出ないように改修します
ご指摘ありがとうございます 🙏 

ちなみにですが、使っている将棋ソフトの名前を教えていただいても良いでしょうか？

**Comment by murosan** [comment]
https://github.com/murosan/shogi-board-server/releases/tag/v1.4.1
改修しました

**Comment by tsukuha** [comment]
@murosan 
対応、ありがとうございます！
利用している将棋ソフトですが、
やねうらおさんがreleaseしている、以下になります。
以下の将棋ソフトでは加えてtimeoutの問題が発生していたのでtimeoutの時間設定も少し手を入れたので、
もしかするとすぐには動かないかもしれませんが、そちらは環境依存かなあとは思うので。

> https://github.com/mizar/YaneuraOu/releases/tag/v7.5.0%2B20220507c.hash128
link: [Suisho5-YaneuraOu-v7.5.0+20220507c.hash128-macos.tar.xz](https://github.com/mizar/YaneuraOu/releases/download/v7.5.0+20220507c.hash128/Suisho5-YaneuraOu-v7.5.0+20220507c.hash128-macos.tar.xz)

**Comment by murosan** [comment]
一度ターミナルで実行できるか試していただけますか？
署名問題で実行できていない可能性がありそうです
```
cd ~/Downloads/Suisho5-YaneuraOu-v7.5.0+20220507c.hash128-macos
./Suisho5_YaneuraOu-macos11-clang++-tournament-applesse42
```
ここで署名問題が出た場合、「システム環境設定」→「一般」から許可して実行しなおします。

実行後、入力待ちになったら `usi` と入力し、オプションと `usiok` という文字列が出力されればOKです。

**Comment by tsukuha** [comment]
@murosan 
実行ファイルは以下のファイルですね
```.sh
cd ~/Downloads/Suisho5-YaneuraOu-v7.5.0+20220507c.hash128-macos
./Suisho5_YaneuraOu-macos11-clang++-tournament-applem1
```

**Comment by tsukuha** [comment]
@murosan 
こちら実行ログになります
```
$ ./Suisho5_YaneuraOu-macos11-clang++-tournament-applem1         
usi
id name Suisho5(20211123)-YaneuraOu
id author yaneurao, tayayan
option name Threads type spin default 4 min 1 max 512
option name USI_Hash type spin default 16 min 1 max 33554432
option name USI_Ponder type check default false
option name Stochastic_Ponder type check default false
option name MultiPV type spin default 1 min 1 max 800
option name NetworkDelay type spin default 120 min 0 max 10000
option name NetworkDelay2 type spin default 1120 min 0 max 10000
option name MinimumThinkingTime type spin default 2000 min 1000 max 100000
option name SlowMover type spin default 100 min 1 max 1000
option name MaxMovesToDraw type spin default 0 min 0 max 100000
option name DepthLimit type spin default 0 min 0 max 2147483647
option name NodesLimit type spin default 0 min 0 max 9223372036854775807
option name EvalDir type string default <internal>
option name WriteDebugLog type string default 
option name GenerateAllLegalMoves type check default false
option name EnteringKingRule type combo default CSARule27 var NoEnteringKing var CSARule24 var CSARule24H var CSARule27 var CSARule27H var TryRule
option name USI_OwnBook type check default true
option name NarrowBook type check default false
option name BookMoves type spin default 16 min 0 max 10000
option name BookIgnoreRate type spin default 0 min 0 max 100
option name BookFile type combo default no_book var no_book var standard_book.db var yaneura_book1.db var yaneura_book2.db var yaneura_book3.db var yaneura_book4.db var user_book1.db var user_book2.db var user_book3.db var book.bin
option name BookDir type string default book
option name BookEvalDiff type spin default 30 min 0 max 99999
option name BookEvalBlackLimit type spin default 0 min -99999 max 99999
option name BookEvalWhiteLimit type spin default -140 min -99999 max 99999
option name BookDepthLimit type spin default 16 min 0 max 99999
option name BookOnTheFly type check default false
option name ConsiderBookMoveCount type check default false
option name BookPvMoves type spin default 8 min 1 max 246
option name IgnoreBookPly type check default false
option name SkillLevel type spin default 20 min 0 max 20
option name DrawValueBlack type spin default -2 min -30000 max 30000
option name DrawValueWhite type spin default -2 min -30000 max 30000
option name PvInterval type spin default 300 min 0 max 100000
option name ResignValue type spin default 99999 min 0 max 99999
option name ConsiderationMode type check default false
option name OutputFailLHPV type check default true
option name FV_SCALE type spin default 24 min 1 max 128
usiok
```

**Comment by murosan** [comment]
ちゃんと実行できてますね。その状態であればちゃんと動きそうです。
もしまだ動かない場合、ログをいただければと 🙏

**Comment by tsukuha** [comment]
@murosan 
ご対応ありがとうございます！
特にソースコードを修正することなく動きました。

**Comment by murosan** [comment]
良かったです！
